apiVersion: apps/v1
kind: besoscerezasDeployment
metadata:
  name: besoscerezas-deployment
spec:
  selector:
      matchLabels:
          run: besoscerezas-container
  replicas: 1
  template:
      metadata:
          labels:
              run: besoscerezas-container
      spec:
        containers:
          - name: besoscerezas-container
            image: ironwolf1212/besoscerezas
            ports:
            - containerPort: 4000
            