apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigw-deployment
spec:
  selector:
      matchLabels:
          run: apigw-container
  replicas: 1
  template:
      metadata:
          labels:
              run: apigw-container
      spec:
        containers:
          - name: apigw-container
            image: danielfroseroz/apigtw:latest
            ports:
            - containerPort: 4000
            env:
                - name: HOTELES_SERVICE
                  value: http://hoteles-service:3000/
                - name: VUELOS_SERVICE
                  value: http://vuelos-service:5000/
                - name: RESTAURANTES_SERVICE
                  value: http://restaurantes-service:8080/

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hoteles-deployment
spec:
  selector:
      matchLabels:
          run: hoteles-container
  replicas: 1
  template:
      metadata:
          labels:
              run: hoteles-container
      spec:
        containers:
          - name: hoteles-container
            image: danielfroseroz/hoteles:1.0.0
            ports:
            - containerPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurantes-deployment
spec:
  selector:
      matchLabels:
          run: restaurantes-container
  replicas: 1
  template:
      metadata:
          labels:
              run: restaurantes-container
      spec:
        containers:
          - name: restaurantes-container
            image: danielfroseroz/restaurantes:1.0.0
            ports:
            - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vuelos-deployment
spec:
  selector:
      matchLabels:
          run: vuelos-container
  replicas: 1
  template:
      metadata:
          labels:
              run: vuelos-container
      spec:
        containers:
          - name: vuelos-container
            image: danielfroseroz/vuelos:1.0.0
            ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: apigw-service
  labels:
    run: apigw-service
spec:   
  type: NodePort
  selector: 
    run: apigw-deployment
  ports:
  - port: 4000
    protocol: TCP
    targetPort: 4000
    nodePort: 30001
---
apiVersion: v1
kind: Service
metadata:
  name: hoteles-service
  labels:
    run: hoteles-service
spec:   
  type: NodePort
  selector:
    run: hoteles-deployment
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30002
---
apiVersion: v1
kind: Service
metadata:
  name: vuelos-service
  labels:
    run: vuelos-service
spec:   
  type: NodePort
  selector:
    run: vuelos-deployment
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30003
---
apiVersion: v1
kind: Service
metadata:
  name: restaurantes-service
  labels:
    run: restaurantes-service
spec:   
  type: NodePort
  selector:
    run: restaurantes-deployment
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30004

