apiVersion: apps/v1
kind: salchipapitasDeployment
metadata:
  name: salchipapitas-deployment
spec:
  selector:
      matchLabels:
          run: salchipapitas-container
  replicas: 1
  template:
      metadata:
          labels:
              run: salchipapitas-container
      spec:
        containers:
          - name: salchipapitas-container
            image: ironwolf1212/salchipapitas
            ports:
            - containerPort: 4000
            